name: CI (Flatpak)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Do not cancel in-progress runs if a labeling action took place (other than 'flatpak'). Otherwise, adding irrelevant
  # labels causes existing runs to be canceled and a new (identical) run to be started.
  cancel-in-progress: ${{ (github.event.action != 'labeled' && github.event.action != 'unlabeled') || github.event.label.name == 'flatpak' }}

jobs:
  CI-Flatpak:
    # Only run this job if the PR has the 'flatpak' label.
    if: |
      github.repository == 'quanticsoul4772/ladybird'
      && contains(github.event.pull_request.labels.*.name, 'flatpak')
    name: Flatpak ${{ matrix.arch }}

    # FIXME: Temporarily run on GitHub runners until Blacksmith runners have overlay redirect_dir enabled.
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64']
        runner_labels: ['["ubuntu-24.04"]']

        include:
          - arch: 'aarch64'
            runner_labels: '["ubuntu-24.04-arm"]'

    secrets: inherit
    uses: ./.github/workflows/flatpak-template.yml
    with:
      arch: ${{ matrix.arch }}
      runner_labels: ${{ matrix.runner_labels }}
