name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  # CI matrix - runs the job in lagom-template.yml with different configurations.
  Lagom:
    if: github.repository == 'LadybirdBrowser/ladybird'

    strategy:
      fail-fast: false
      matrix:
        os_name: ['Linux']
        os: [ubuntu-24.04]
        fuzzer: ['NO_FUZZ']
        toolchain: ['GNU']
        clang_plugins: [false]

        include:
          - os_name: 'Linux'
            os: ubuntu-24.04
            fuzzer: 'NO_FUZZ'
            toolchain: 'Clang'
            clang_plugins: true

          - os_name: 'macOS'
            os: macos-15
            fuzzer: 'NO_FUZZ'
            toolchain: 'Clang'
            clang_plugins: false

          - os_name: 'Linux'
            os: ubuntu-24.04
            fuzzer: 'FUZZ'
            toolchain: 'Clang'
            clang_plugins: false

    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      os_name: ${{ matrix.os_name }}
      os: ${{ matrix.os }}
      fuzzer: ${{ matrix.fuzzer }}
      clang_plugins: ${{ matrix.clang_plugins }}
