name: 'Close stale PRs'
on:
  # Run daily at 01:30.
  schedule:
    - cron: '30 1 * * *'

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  stale:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: github.repository == 'LadybirdBrowser/ladybird'
    permissions:
      actions: write  # required for cache management (see https://github.com/actions/stale/issues/1133)
      pull-requests: write
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d  # v10.1.1
        with:
          operations-per-run: 500

          # Leave issues alone.
          days-before-issue-stale: -1
          days-before-issue-close: -1

          # PRs become stale after 21 days of inactivity.
          days-before-pr-stale: 21
          stale-pr-label: stale
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had recent activity. It will be
            closed in 7 days if no further activity occurs. Thank you for your contributions!

          # PRs get closed after 30 days (21 + 7) of inactivity
          days-before-pr-close: 7
          close-pr-message: >
            This pull request has been closed because it has not had recent activity. Feel free to open a new pull
            request if you wish to still contribute these changes. Thank you for your contributions!
